export const commonAttributes = {
    input: [
        "accept",
        "alt",
        "autocomplete",
        "autofocus",
        "checked",
        "dirname",
        "disabled",
        "form",
        "formaction",
        "height",
        "list",
        "max",
        "maxlength",
        "min",
        "multiple",
        "name",
        "onload",
        "onsearch",
        "pattern",
        "placeholder",
        "popovertarget",
        "popovertargetaction",
        "readonly",
        "required",
        "size",
        "src",
        "step",
        "type",
        "value",
        "width",
    ],
    form: [
        "accept-charset",
        "action",
        "autocomplete",
        "enctype",
        "method",
        "name",
        "novalidate",
        "onreset",
        "onsubmit",
        "rel",
        "target",
    ],
    area: [
        "alt",
        "coords",
        "download",
        "href",
        "hreflang",
        "media",
        "rel",
        "shape",
        "target",
    ],
    img: [
        "alt",
        "height",
        "ismap",
        "onabort",
        "onerror",
        "onload",
        "sizes",
        "src",
        "srcset",
        "usemap",
        "width",
    ],
    script: ["async", "charset", "defer", "onerror", "onload", "src", "type"],
    button: [
        "autofocus",
        "disabled",
        "form",
        "formaction",
        "name",
        "popovertarget",
        "popovertargetaction",
        "type",
        "value",
    ],
    select: [
        "autofocus",
        "disabled",
        "form",
        "multiple",
        "name",
        "required",
        "size",
    ],
    textarea: [
        "autofocus",
        "cols",
        "dirname",
        "disabled",
        "form",
        "maxlength",
        "name",
        "placeholder",
        "readonly",
        "required",
        "rows",
        "wrap",
    ],
    audio: [
        "autoplay",
        "controls",
        "loop",
        "muted",
        "onabort",
        "oncanplay",
        "oncanplaythrough",
        "ondurationchange",
        "onemptied",
        "onended",
        "onerror",
        "onloadeddata",
        "onloadedmetadata",
        "onloadstart",
        "onpause",
        "onplay",
        "onplaying",
        "onprogress",
        "onratechange",
        "onseeked",
        "onseeking",
        "onstalled",
        "onsuspend",
        "ontimeupdate",
        "onvolumechange",
        "onwaiting",
        "preload",
        "src",
    ],
    video: [
        "autoplay",
        "controls",
        "height",
        "loop",
        "muted",
        "onabort",
        "oncanplay",
        "oncanplaythrough",
        "ondurationchange",
        "onemptied",
        "onended",
        "onerror",
        "onloadeddata",
        "onloadedmetadata",
        "onloadstart",
        "onpause",
        "onplay",
        "onplaying",
        "onprogress",
        "onratechange",
        "onseeked",
        "onseeking",
        "onstalled",
        "onsuspend",
        "ontimeupdate",
        "onvolumechange",
        "onwaiting",
        "poster",
        "preload",
        "src",
        "width",
    ],
    meta: ["charset", "content", "http-equiv", "name"],
    del: ["cite", "datetime"],
    ins: ["cite", "datetime"],
    td: ["colspan", "headers", "rowspan"],
    th: ["colspan", "headers", "rowspan", "scope"],
    object: [
        "data",
        "form",
        "height",
        "name",
        "onabort",
        "oncanplay",
        "onerror",
        "type",
        "usemap",
        "width",
    ],
    time: ["datetime"],
    track: [
        "default",
        "kind",
        "label",
        "oncuechange",
        "oncuechange",
        "src",
        "srclang",
    ],
    fieldset: ["disabled", "form", "name"],
    option: ["disabled", "label", "selected", "value"],
    a: ["download", "href", "hreflang", "media", "rel", "target", "type"],
    output: ["for", "form", "name"],
    meter: ["form", "high", "low", "max", "min", "optimum", "value"],
    embed: [
        "height",
        "onabort",
        "oncanplay",
        "onerror",
        "src",
        "type",
        "width",
    ],
    iframe: ["height", "name", "onload", "sandbox", "src", "srcdoc", "width"],
    base: ["href", "target"],
    link: ["href", "hreflang", "media", "onload", "rel", "sizes", "type"],
    optgroup: ["label"],
    progress: ["max", "value"],
    source: ["media", "sizes", "src", "srcset", "type"],
    style: ["media", "onerror", "onload", "type"],
    map: ["name"],
    param: ["name", "value"],
    body: [
        "onafterprint",
        "onbeforeprint",
        "onbeforeunload",
        "onerror",
        "onhashchange",
        "onload",
        "onoffline",
        "ononline",
        "onpageshow",
        "onresize",
        "onunload",
    ],
    details: ["ontoggle", "open"],
    ol: ["reversed", "start"],
    col: ["span"],
    colgroup: ["span"],
    menu: ["type"],
    li: ["value"],
    "Global Attributes": [
        "class",
        "contenteditable",
        "data-*",
        "dir",
        "draggable",
        "enterkeyhint",
        "hidden",
        "id",
        "inert",
        "inputmode",
        "lang",
        "popover",
        "spellcheck",
        "style",
        "tabindex",
        "title",
        "translate",
    ],
};
