export const DUMMY_DATA = [
  {
    id: 1,
    title: "노션을 만들자",
    content: "즐거운 자바스크립트의 세계!",
    documents: [
      {
        id: 1,
        title: "실험용",
        content: "하위 문서입니다.",
        documents: [
          {
            id: 1,
            title: "실험용의 하위 문서",
            content: "하위의 하위 문서입니다.",
            documents: [],
            createdAt: "",
            updatedAt: "",
          },
          {
            id: 2,
            title: "실험용의 하위 문서2",
            content: "하위의 하위 문서2입니다.",
            documents: [],
            createdAt: "",
            updatedAt: "",
          },
        ],
        createdAt: "",
        updatedAt: "",
      },
      {
        id: 2,
        title: "더미데이터",
        content: "더미데이터입니다.",
        documents: [],
        createdAt: "",
        updatedAt: "",
      },
      {
        id: 3,
        title: "성공해라",
        content: "성공했으면 좋겠네요.",
        documents: [],
        createdAt: "",
        updatedAt: "",
      },
    ],
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 2,
    title: "노션을 만들자2",
    content: "슬픈 코딩의 세계!",
    documents: [
      {
        id: 1,
        title: "실험용",
        documents: [],
        createdAt: "",
        updatedAt: "",
      },
      {
        id: 2,
        title: "더미데이터",
        documents: [],
        createdAt: "",
        updatedAt: "",
      },
      {
        id: 3,
        title: "성공해라",
        documents: [],
        createdAt: "",
        updatedAt: "",
      },
    ],
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 3,
    title: "노션을 만들자3",
    content: "행복하니? 아니~",
    documents: [],
    createdAt: "",
    updatedAt: "",
  },
];
