import App from "./App.js";
import documentsReducer from "./modules/documentsDuck.js";
import { createStore } from "./utils/myRedux/createStore.js";
import thunk from "./utils/myRedux/thunk.js";
import Observer from "./utils/observer/Observable.js";
const observer = Object.freeze(new Observer());
const store = createStore(documentsReducer, thunk);
export { store, observer };
const $app = document.getElementById("app");
new App({ $target: $app });
